### ISSUE TITLE
Missing Texture [Curio Slots]

### ISSUE THREAD

**Issue by JustAHuman-xD** [PINPAL/VaultHuntersDarkUI#1]
![image](https://user-images.githubusercontent.com/65748158/194965219-15e462cf-a857-4f3e-9eb3-035ea046cf99.png)
As you can see in the above image the curio menu is still the default ui

**Comment by PINPAL** [comment]
Apologisies for the delay been very busy lately, this should be fixed in the latest release:
https://github.com/PINPAL/VaultHuntersDarkUI/releases/tag/1.3

Please let me know if this resolves the issue so I can close the issue. Thanks :D

**Comment by JustAHuman-xD** [comment]
Oh my gosh sorry I didn't see you responded! I'll double check when im home and if so I'll close it
